### ISSUE TITLE
NSO N64 Controller problems

### ISSUE THREAD

**Issue by jeremania** [darthcloud/BlueRetro#468]
The NSO N64 Controller syncs fine and works well for about 10 minutes or so... then it will consistently move to an odd state where the controller still appears to be connected, but inputs no longer work and lots of random, uncommanded inputs will register. If I power off the controller the random inputs continue, which indicates that something is going on with BlueRetro. 

I have play tested the same setup for hours with a PS5 DualSense controller without any issues. The problem appears to be unique to the NSO N64 Controller. I've yet to test a Switch Pro controller, but will try it next.

N64 motherboard revision: NUS-CPU-05
List of internal mods installed: BlueRetro, N64Digital, Noctua fan mod
Other external peripheral used: NSO N64 Controller, ReN64 PSU

**Comment by Felipe0604** [comment]
I have the same issue with the same configuration. The controller is getting disconnected after 10 minutes when using NSO 64 Controller with a blue retro adapter. The issue is only present when the device is updated to version 1.8 or 1.9, but if I revert to version 1.7, the device works flawlessly.

N64 motherboard: NUS-CPU-05-01
Adapter: BlueRetro N64
Mods: N64Digital with new flex cable, and recap.

**Comment by darthcloud** [comment]
Fix is now in v1.9.1
